/* Vercel build step for the Nestick frontend.
 *
 * Copies the static control-panel from nestick/web/static into dist/ and
 * generates a config.js with the backend (Render) API base. app.js reads
 * window.NESTICK_API_BASE, falling back to same-origin when unset.
 *
 * Requires NESTICK_API_BASE (the Render service URL), e.g.
 *   https://nestick.onrender.com
 */
const fs = require("fs");
const path = require("path");

const DIST = path.join(__dirname, "dist");
const SRC = path.join(__dirname, "..", "..", "nestick", "web", "static");

const API_BASE = (process.env.NESTICK_API_BASE || "").replace(/\/+$/, "");

fs.rmSync(DIST, { recursive: true, force: true });

// Keep the /static/ URL shape the HTML already references.
fs.cpSync(SRC, path.join(DIST, "static"), { recursive: true });

// Backend location for the frontend.
fs.writeFileSync(
  path.join(DIST, "config.js"),
  `/* generated by build.js -- do not edit */\n` +
    `window.NESTICK_API_BASE = ${JSON.stringify(API_BASE)};\n`,
  "utf8"
);

// Load config.js before app.js so API_BASE is set when the app boots.
const html = fs.readFileSync(path.join(SRC, "index.html"), "utf8");
const patched = html.replace(
  '<script src="/static/app.js"></script>',
  '<script src="/config.js"></script>\n<script src="/static/app.js"></script>'
);
if (patched === html) {
  throw new Error("index.html: script patch target not found");
}
fs.writeFileSync(path.join(DIST, "index.html"), patched, "utf8");

console.log(`Built ${DIST}: assets + config.js (NESTICK_API_BASE=${API_BASE || "(same-origin)"})`);
